// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuqq26yin2nJhXru_gdcWcPxPBJDdUAc',
    appId: '1:15819154592:web:93392acc71659addb295c5',
    messagingSenderId: '15819154592',
    projectId: 'ugbills-b101d',
    authDomain: 'ugbills-b101d.firebaseapp.com',
    storageBucket: 'ugbills-b101d.firebasestorage.app',
    measurementId: 'G-VHM2CE1QNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuW31xieJxc0gEYSixMCaCp2IOK5hHPs',
    appId: '1:15819154592:android:6ecb1c2cface40dfb295c5',
    messagingSenderId: '15819154592',
    projectId: 'ugbills-b101d',
    storageBucket: 'ugbills-b101d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzBdcT_qIFcJWNgw1xwmoWLEUgxuRu-o',
    appId: '1:15819154592:ios:bde252da1fe40a95b295c5',
    messagingSenderId: '15819154592',
    projectId: 'ugbills-b101d',
    storageBucket: 'ugbills-b101d.firebasestorage.app',
    iosBundleId: 'com.zgt.ugbills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzBdcT_qIFcJWNgw1xwmoWLEUgxuRu-o',
    appId: '1:15819154592:ios:8df939f7aa5f2b76b295c5',
    messagingSenderId: '15819154592',
    projectId: 'ugbills-b101d',
    storageBucket: 'ugbills-b101d.firebasestorage.app',
    iosBundleId: 'com.example.ugbills',
  );
}
