// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByzwsdMDH9FN3IX6fpS7qQFB7PO3-5Ck8',
    appId: '1:28085771925:web:43dbc79b892cf84f88059c',
    messagingSenderId: '28085771925',
    projectId: 'zeelpay',
    authDomain: 'zeelpay.firebaseapp.com',
    storageBucket: 'zeelpay.firebasestorage.app',
    measurementId: 'G-80QBPHBRD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxOFP0qfuWQTejFVD94vn-PUXZV-t3jHs',
    appId: '1:28085771925:android:033118a1903a6db988059c',
    messagingSenderId: '28085771925',
    projectId: 'zeelpay',
    storageBucket: 'zeelpay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA933892xKDY6vP0XSdM7NKj4X7mOG3RR8',
    appId: '1:28085771925:ios:13b90009754a3ee688059c',
    messagingSenderId: '28085771925',
    projectId: 'zeelpay',
    storageBucket: 'zeelpay.firebasestorage.app',
    iosBundleId: 'com.zgt.zeelpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA933892xKDY6vP0XSdM7NKj4X7mOG3RR8',
    appId: '1:28085771925:ios:ec731d76b5d66b2d88059c',
    messagingSenderId: '28085771925',
    projectId: 'zeelpay',
    storageBucket: 'zeelpay.firebasestorage.app',
    iosBundleId: 'com.example.zealpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByzwsdMDH9FN3IX6fpS7qQFB7PO3-5Ck8',
    appId: '1:28085771925:web:a8e8aa67b065cb5288059c',
    messagingSenderId: '28085771925',
    projectId: 'zeelpay',
    authDomain: 'zeelpay.firebaseapp.com',
    storageBucket: 'zeelpay.firebasestorage.app',
    measurementId: 'G-84HFSMQ953',
  );
}
